project:
  type: website

website:
  title: "Running shiny & code in quarto document"
  navbar:
    left:
      - href: index.qmd
        text: Shiny
      - href: code_chunk.qmd
        text: Code
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



